### ISSUE TITLE
Uses "Literal" from typing which is 3.8+ only

### ISSUE THREAD

**Issue by palfrey** [intgr/drf-yasg-stubs#3]
See https://docs.python.org/3/library/typing.html#typing.Literal

I think the project should either document the Python 3.8 requirement or remove it and test against earlier versions.

Thanks for all your work here!

**Comment by intgr** [comment]
This is true, but should not cause any issues for users even with Python 3.7 or earlier.

The `.pyi` files are never executed by the Python interpreter itself. They are read by third party type-checking packages, like mypy. If you use mypy on Python 3.7, it has built-in knowledge of `typing.Literal` even if the interpreter doesn't.

If you're having problems with earlier Python versions, please describe your setup.

**Comment by palfrey** [comment]
In a project where I've got a slightly hacked version of the views.pyi (to fix https://github.com/intgr/drf-yasg-stubs/issues/2) I get the following unless I remove the `Literal` references. This is with mypy called as `MYPYPATH=stubs mypy .`. OTOH, this doesn't occur with the stock stubs, so I think this is just a local stubs weirdness.

> stubs/drf_yasg/views.pyi:5: error: Module 'typing' has no attribute 'Literal'
